### ISSUE TITLE
dwmblocks battery and volume no longer working

### ISSUE THREAD

**Issue by sbkucin** [LukeSmithxyz/dwm#137]
The icons for battery and volume are no longer functioning, just get "unknown" in their place.  I reinstalled larbs to see if that would fix it, but still same issue.  Also when you write to dwmblocks config.h file in vim, it gives you an error, dmenupass, line 6 pipe broken, but when you comment out volume and battery, it works fine.  Not sure what do to at this point, any suggestions?

**Comment by LukeSmithxyz** [comment]
As in "unknown" is literally written in the status bar? What happens if your run `battery` or `volume` in the command line?

Minor possibility that this might be related to https://github.com/LukeSmithxyz/voidrice/issues/844 which I haven't experienced either.

**Comment by sbkucin** [comment]
Battery: “Uknown 95” plugged in
“Discharging 95” unplugged 


Volume: “ On 68” which is what the current volume level is set to, but I am not sure what happened to the icons for both of them

**Comment by sbkucin** [comment]
It’s like the scripts are no longer working for battery and volume, but work fine when you run them in the terminal

**Comment by sbkucin** [comment]
One last thing, you can no longer left click on the date for the calendar, but all the other ones still work: newsboat, weather, help, network

**Comment by kronikpillow** [comment]
calendar perfectly clickable to me

**Comment by sbkucin** [comment]
So I had commented out "volume" in dwmblocks, but when I went to re-activate "volume to see if I can get it working correctly, I get this, when the script runs to automatically update dwmblocks:

"config.h" 36L, 1461C written
:!cd ~/.local/src/dwmblocks/; sudo make install && { killall -q dwmblocks;setsid -f dwmblocks }
/home/sbkucin/.local/bin/dmenupass: line 6: echo: write error: Broken pipe
gcc -c dwmblocks.c
gcc dwmblocks.o -lX11 -o dwmblocks
mkdir -p /usr/local/bin
cp -f dwmblocks /usr/local/bin
chmod 755 /usr/local/bin/dwmblocks

I don't get the "Broken pipe" on the say "weather" which is working correctly I un-comment it in the config file, but with "volume" I do.

**Comment by LukeSmithxyz** [comment]
The dmenupass error is not relevant to this issue.

**Comment by sbkucin** [comment]
So I don’t know what went wrong, but I think it had something to do with the distro I was using, I went back to using Manjaro, everything is fine now, and I got to learn new things about dwmblocks  and the scripts.  Thank you for your time .

**Comment by anntnzrb** [comment]
This will sound very odd but I remember something similar happening, I just noticed at the typo here "_Uknown_" :

> Battery: “Uknown 95” plugged in “Discharging 95” unplugged Volume: “ On 68” which is what the current volume level is set to, but I am not sure what happened to the icons for both of them

I don't know how I fixed nor I am able to find the commit where I corrected this, but I **do** remember conlcuding it was a typo; @sbkucin can you confirm this typo is present or was it your fault?

I'm asking because there are inconsistencies in your issue, at the beggining you stated:

> The icons for battery and volume are no longer functioning, just get "unknown" in their place

... where we can clearly see the typo is not present.

Please post the _literal_ error you're getting.

As for now, I can assure this is un-related to this repo (dwm); this is specifically a "something" on the [battery](https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/statusbar/battery) script on Luke's dotfiles.

---

I suggest splitting your errors in separate issues (respectively in their own repos as well), because you are mixing some stuff in here, either that or provide a bit more technical details with literal output of the present errors.

**Comment by tramhao** [comment]
I met similar problem. Run a command:
which volume
found that I have another program called volume in my /usr/bin directory, which is coming from i3 package. Rename this one and volume icon works.

**Comment by LukeSmithxyz** [comment]
@tramhao That would make sense. I've had to rename some of these scripts in the past because of conflicts due to their generic names. I might just hard-code the paths in dwmblocks or prefix all the scripts with something so they are unique.

**Comment by LukeSmithxyz** [comment]
I've renamed the scripts, prefixing them all with `sb-`. This should permanently fix this issue.

To fix this, update both the voidrice repository and the dwmblocks repo and recompile dwmblocks, or manually rename the scripts and how they are called in dwmblocks.
