### ISSUE TITLE
rewrite in rust

### ISSUE THREAD

**Issue by twelveseas** [LukeSmithxyz/dwm#154]
You should rewrite your build in rust so its modern, a lot faster and not insecure. thanks. bye.

**Comment by kdkasad** [comment]
> You should rewrite your build in rust so its modern, a lot faster and not insecure. thanks. bye.

There's nothing wrong with C. The language a program is written in does not dictate whether or not it's fast and secure. DWM is written to be both fast and secure. Plus, the codebase has been tested for years. Rewriting the whole thing in another language is more likely to introduce bugs and issues than leaving it in C.

Also, Rust is not necessarily any faster than C. Again, it's up to well-written code, not just the language. Additionaly, the Rust port of Xlib is just a wrapper around the C library. So you'd probably lose performance by rewriting DWM in Rust.

If you really want a performance/security increase, the best course of action would likely be to replace Xlib with XCB in the existing DWM code.

Please consider the actual benefits and costs before telling someone to rewrite a perfectly fine program in another language just because it's newer/more "modern".

That being said, if *you* want to rewrite DWM in Rust, go ahead!

**Comment by LukeSmithxyz** [comment]
Please post this issue on suckless's upstream so they can laugh at you instead.
