### ISSUE TITLE
DWM won't start on Arch Linux

### ISSUE THREAD

**Issue by SingularisArt** [LukeSmithxyz/dwm#183]
Hello all.

I have a copied, but modified version of this repo, which you can view [here](https://github.com/SingularisArt/Singularis/tree/master/aspects/dwm).

Here's what my .xprofile has:

```bash
exec startx dwm
```

But, when I login using `lxdm`, `lightdm`, etc, they all just kick me back to the login page. This is my first time installing arch.
Can someone help me? I don't know what to do.

**Comment by jiploading** [comment]
you should have a `dwm.desktop` file in your `/usr/share/xsessions` directory in order to start dwm with any graphical login manager. In that case you don't need `.xprofile` .
just put following lines in your `/usr/share/xsessions/dwm.desktop` file.
```
[Desktop Entry]
Encoding=UTF-8
Name=Dwm
Comment=Dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
```
If you don't have `/usr/share/xsessions/dwm.desktop` file then create one. Then at the login screen on your login manager select dwm and go ahead.

**Comment by narukeh** [comment]
@jiploading You should be using XINITRC and it should look line this:
`cat ~/.xinitrc`
```bash
#!/bin/sh

#In xprofile you put programs that u want to autostart
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

#And then you start your WM/DE
exec dwm
```
----
Yes, if you want to use a login manager you got to have a .desktop file.
Dont forget to close this "issue".

**Comment by SingularisArt** [comment]
Thanks for your responses. I got it to fix. I just had an error in my `config.h` file.

For those of you wondering, I just added a font that I didn't have! Have a great day! 😃
