### ISSUE TITLE
can we have a system tray

### ISSUE THREAD

**Issue by i9nite** [LukeSmithxyz/dwm#184]
I trayed to patch systray (https://dwm.suckless.org/patches/systray/) but I got a lot of errors :(
can we have the patch in this fork if not, can anyone please help me patch it?

**Comment by JimPix1** [comment]
The systray patch is quite large and if you don't know C you don't really have much hope of manually patching the failed hunks yourself with Luke's build since it already has a lot of patches.
I would have liked a systray myself but I've come to just live without it, most programs have systray settings allowing you to disable it anyway

**Comment by i9nite** [comment]
> The systray patch is quite large and if you don't know C you don't really have much hope of manually patching the failed hunks yourself with Luke's build since it already has a lot of patches. I would have liked a systray myself but I've come to just live without it, most programs have systray settings allowing you to disable it anyway

I forked MentalOutlaw's DWM and added systray patch and most other patchs that Luke have
