### ISSUE TITLE
Window resize not working

### ISSUE THREAD

**Issue by ui3o** [LukeSmithxyz/dwm#22]
Hi Luke!

I am a programmer and can not find the solution how can I resolve the window resize issue in dwm. I post the issue here, because I hope you can help me thinking, how I can fix this. I have google for a long time, to find the solution, but I did not find it.

I attach a picture about the situation. When I resize the window, after the minimum size of the window reached, I can not make it smaller. In floating layout it does not matter, but in other layout it is so bad, because it is over then the others.

Thank you for your answer! 

![2020-03-23 12-10](https://user-images.githubusercontent.com/43638725/77310911-70041f00-6cff-11ea-92b9-283263622202.gif)

**Comment by kronikpillow** [comment]
window resize is working in dwm and in luke's dwm, but by default in dwm windows can only be resized from the bottom right corner, you need to patch dwm with the resizecorners patch which can be found on suckless's website, dwm as dwm is intended to be bare minimal (up to a maximum of 2000 lines of code), and any additional functionality you want you either need to patch the source code from the patch repository, or to code your own patches

**Comment by ui3o** [comment]
As I wrote, I know how the dwm works. The issue is not about the bottom right corner. The sample only shows not possible to resize some windows. 

In the attached picture you can see, I can not resize the upper window, but the downer (it is a terminal), possible to resize. Same method. Some window enable to resize, some not (like chromium also).
If you know the patch which resolve this issue, please help me! Thank you

**Comment by LukeSmithxyz** [comment]
I don't really understand why having gui windows minimize to under their own minimum would be a good feature to have. This is definitely working as intended.

**Comment by ui3o** [comment]
Here is the real problem. I attach a new picture about it.

I wrote a new layout. It is same as master stack, but the master in the middle. When I resize the master, and the slaves on the sides can not be smaller as there minimum, which case they are over to the master.

![window-resize-2](https://user-images.githubusercontent.com/43638725/77849662-8dd4f680-71cd-11ea-9be8-02b0d734d1f5.gif)

**Comment by ui3o** [comment]
And of course I set all windows to the same size on the left side, but the virtualbox window is a litle bit bigger, and you can see the terminal is outside on the bottom then the others, and also they are going to under to the master...
When I set the window size to same size on the left side, I think in dwm can not resize the window under the minimum size, that is why this happen. In i3wm and bspwm this works well.

**Comment by kronikpillow** [comment]
ahhh that's because luke's build is set to respect resizehints, eg some apps have a minimum size specification in their programming, like discord, so when you try to resize it bellow the minimum it doesn't allow you to, if you want to disable this feature go to your config.h and search for resizehints and set it to 0, rebuild your dwm, restart it, and now all windows will resize even thou you are going bellow the expected minimum size of the app, or you can use the centered floating master layout for these kind of windows, honestly I got really addicted to the centered floating master in combination with the stacker patch, stacker is crucial to using this layout in my opinion :) although to use stacker you would need to rebind some of luke's default bindings, but it's not like you really need all of them for your own workflow :)

**Comment by ui3o** [comment]
Thank you so much! This fixed my issue! :)
