### ISSUE TITLE
not a issue but a question

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwm#48]
Hey luke, I'm trying to run xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }' to see what the key symbols for my keylayouts are so that i can modify your keybinding to my likings, but now the swallow patch completely swallows it and I can't see the key symbols in the background, as before it used to pop up the app in a separate window, and used to print the data to the terminal, now the app gets spawned inside the terminal or the terminal gets swallowed ... I have tried setting St to noswallow 1, but it didn't help

**Comment by LukeSmithxyz** [comment]
Does `setsid xev &` work?

**Comment by kronikpillow** [comment]
yes it does! thank you luke!

**Comment by kronikpillow** [comment]
actually it doesn't :-/ it worked for me because I changed St to isterminal 0 ... but once I return St to isterminal 1 it doesn't work :-/

**Comment by LukeSmithxyz** [comment]
`setsid xev &` works fine on my machine whether St has `isterminal` 0 or 1. That's all I can say.

Although it's hard to pipe xev through other commands running it in setsid, you can easily get the same functionality by adding the line to a script/subscript and running it.

**Comment by LukeSmithxyz** [comment]
Okay, regardless of using `setsid`, `xev` should now automatically not swallow its parent terminal no matter what due to the bug fix in https://github.com/LukeSmithxyz/dwm/commit/c4f45fafac88d8e800abe1958116855ff172933e and my addition of a rule for `xev` in https://github.com/LukeSmithxyz/dwm/commit/b9e9ed13818fa3cb18f421968bb75296157ca61c.
