### ISSUE TITLE
Centered floating windows?

### ISSUE THREAD

**Issue by ghost** [LukeSmithxyz/dwm#51]
Are you planning on including centered floating windows in the future (e.g. with the center patch)? 
I have been trying to apply the patch myself but it always fails, even when I manually edit the lines, so I am probably too inexperienced in C to find the reason for it failing...

**Comment by kronikpillow** [comment]
the centered patch is essential to @LukeSmithxyz scratchpad's recent update, as the current scratchpad automatically centers all scratchpads in the middle of the screen, while there is an additional patch for the current scratchpad that disables that feature, and then with the centered patch you could assign the main scratchpad to be centered, while you could have the calculator or other scratchpads appear as floating windows on different parts of your screen

**Comment by paniash** [comment]
@electronblue Maybe patch it yourself?
https://dwm.suckless.org/patches/alwayscenter/

I use this and it works perfectly.

**Comment by goldcoders** [comment]
@electronblue  if u need a patch on that , mine is identical to luke main repo but i patch center floating windows...
and other patches like system try, pertag patch, and cool start patch..

https://github.com/goldcoders/dwm

if u wanna use it you need to transfer .xprofile startup script to your config.h in dwm

@electronblue  you dont need to be good at C, im not a C dev, all you need is learn to read the code 
the lines where it should be added, your having hard time maybe because you are not used to patching
or git... but patching literrally has nothing to do with C.
