### ISSUE TITLE
mpv audio continues to play if parent terminal is closed

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/dwm#65]
I believe this is due to the swallow patch.

If you open an mpv audio file from lf, then close that terminal with `super+q`, the audio sometimes continues to play. You must kill the instance or let it play out.

If you close out of mpv with `q` beforehand, however. This error does not happen.

**Comment by Bear-LB** [comment]
How do you close the terminal window if the terminal window is replaced by mpv. 
Even if i kill the 'st -e lf' process while mpv is running, mpv closes as well because it's a child process of 'st -e lf'.
I cannot reproduce (sterile)

**Comment by LukeSmithxyz** [comment]
I'm talking about opening an audio file only, when there is no video or
album art to swallow the terminal.

**Comment by Bear-LB** [comment]
Right... 
I can reproduce the issue by using lf-git AUR package, which uses HEAD version. I think you use that package as well.

I used the LF AUR package, which uses version r14.
I tested it many times with both packages, as i didn't expect that to be the fix, but that seems to be it.

So yea try this package.
https://aur.archlinux.org/packages/lf/
instead of the git version
