### ISSUE TITLE
Not displaying unicode

### ISSUE THREAD

**Issue by gtLara** [LukeSmithxyz/dwm#77]
I am unable to read unicode characters with this build of dwm. I imagine that Luke or others who use this repo don't have this problem, and I was wondering if anyone had it upon cloning and if so how they solved it, as this is turning out to be a major pain for me. Any help is appreciated :))

I am also using Luke's build of ST (maybe thats relevant) and made sure to undo any changes I had made to the build prior to raising this issue. I have seen some solutions indicate de pango patch, but that is long outdated.

**Comment by drake-newell** [comment]
libXft-bgra

**Comment by kroppt** [comment]
Make sure you're using a font that supports unicode characters. In his configuration for dwm, Luke uses `monospace`, which references the `~/.config/fontconfig/fonts.conf` file, which should be configured. Alternatively, just name the font where the config uses `monospace`, e.g. `Noto Mono`.

**Comment by gtLara** [comment]
Installing fonts as @kroppt suggested partially worked (still not displaying Japanese characters). Closing issue nonetheless.

**Comment by kroppt** [comment]
Since Japanese wasn't working for me, I set out to solve that. I detailed the solution below.

I installed the Noto CJK fonts and registered aliases for them in my font config like so:
```xml
<alias>
  <family>cjk-serif</family>
  <prefer>
    <family>Noto Serif CJK KR</family>
    <family>Noto Serif CJK HK</family>
    <family>Noto Serif CJK JP</family>
    <family>Noto Serif CJK SC</family>
    <family>Noto Serif CJK TC</family>
  </prefer>
</alias>
<alias>
  <family>cjk-sans</family>
  <prefer>
    <family>Noto Sans CJK KR</family>
    <family>Noto Sans CJK HK</family>
    <family>Noto Sans CJK JP</family>
    <family>Noto Sans CJK SC</family>
    <family>Noto Sans CJK TC</family>
  </prefer>
</alias>
<alias>
  <family>cjk-mono</family>
  <prefer>
    <family>Noto Sans Mono CJK KR</family>
    <family>Noto Sans Mono CJK HK</family>
    <family>Noto Sans Mono CJK JP</family>
    <family>Noto Sans Mono CJK SC</family>
    <family>Noto Sans Mono CJK TC</family>
  </prefer>
</alias>
```

Then, I added `cjk-sans`, `cjk-serif`, and `cjk-mono` to the family lists of the `sans`, `serif`, and `monospace` aliases respectively, which I have been using.
E.g.
```xml
<alias>
  <family>serif</family>
  <prefer>
    <family>Noto Serif</family>
    <family>Liberation Serif</family>
    <family>cjk-serif</family>
    <family>Noto Color Emoji</family>
  </prefer>
</alias>
```

And now, Japanese works for me in my web browser (fonts set to Sans, Serif, and Monospace), dwm (font list includes monospace), and st (font set to monospace). Because I am using the patched libXft, I also have full color emoji support.

Just to note that I am not using Luke's build of dwm, just regular old dwm with patches.
